export interface ChoicenessModels{
  img:Resource,
  title:string,
}

export const choicenessModels:ChoicenessModels[]=[
  {
    img:$rawfile('sourcesChoices01.jpeg'),
    title:'我用了4年，去弥补18岁的遗憾'
  },
  {
    img:$rawfile('sourcesChoices02.jpeg'),
    title:'每一次推倒重来，只为在历练中成长'
  },{
    img:$rawfile('sourcesChoices03.jpeg'),
    title:'逃离精神内耗，29岁再出发'
  },{
    img:$rawfile('sourcesChoices04.jpeg'),
    title:'始于低估，奔赴大洋彼岸的约定'
  },{
    img:$rawfile('sourcesChoices05.jpeg'),
    title:'广漂四年，在陌生城市寻找自己'
  },{
    img:$rawfile('sourcesChoices06.png'),
    title:'做自己的小小英雄，在细水长流的坚持里'
  },{
    img:$rawfile('sourcesChoices07.jpeg'),
    title:'28岁，觉醒之后才是真正的人生'
  },{
    img:$rawfile('sourcesChoices08.jpeg'),
    title:'未来的地质人，为热爱奔赴山海'
  },
]