export interface KaoyanTabsModels{
  id:string
  img:string
  title:string
  price:string
}

// export const kaoyanTabsModels:KaoyanTabsModels[]=[
//   {
//     img:$rawfile('ky1.jpg'),
//     title:'邀好友买考研训练营，得现金红包',
//     price: '免费',
//   },
//   {
//     img:$rawfile('ky2.jpg'),
//     title:'25考研训练营 | 享1年扇贝大会员',
//     price: '￥499',
//   },
//   {
//     img:$rawfile('ky3.jpg'),
//     title:'【新课】学规划 | 25考研英语规划',
//     price: '免费',
//   },
//   {
//     img:$rawfile('ky4.jpg'),
//     title:'刷真题 | 考研阅读刷题课',
//     price: '免费',
//   },
//   {
//     img:$rawfile('ky5.jpg'),
//     title:'学策略 | 考研暑假抢跑攻略',
//     price: '免费',
//   },
//   {
//     img:$rawfile('ky6.jpg'),
//     title:'学技巧 | 考研阅读例证题',
//     price: '免费',
//   },
//   {
//     img:$rawfile('ky7.jpg'),
//     title:'考研体验课 | 7天寻求小蜕变',
//     price: '免费',
//   },
//   {
//     img:$rawfile('ky8.jpg'),
//     title:'考研真题宝 | 帮你吃透真题！',
//     price: '￥12',
//   },
//
// ]